### ISSUE TITLE
`_default_` doesn't work with a a callable `output`

### ISSUE THREAD

**Issue by dgjustice** [dmulyalin/fakenos#2]
Awesome lib!  Of course, I tried to color outside the lines right off the bat.  I believe I can work around this, but curious what your thoughts are.  It might be worthy of a documentation note.  I am still kicking the tires on my approach, so I am not sure how badly I "need" this particular corner case.

```python
commands = {
    "_default_": {
        "output": some_func,
    },
}
```

**Comment by dmulyalin** [comment]
Postprocessing should work, what error are you getting when trying to use default with callable?

**Comment by dgjustice** [comment]
Thanks for the quick reply!  Here's the breakdown...

```python
name = "FakeCisco"

initial_prompt = "{base_prompt}#"

def foo(*args, **kwargs):
    return '42'

commands = {
    "_default_": {
        "output": foo,
    }
}
```

Here is the order of operations:

- `ret` is our function [here](https://github.com/dmulyalin/fakenos/blob/master/fakenos/plugins/shell/cmd_shell.py#L119).
- it fails the key lookup [here](https://github.com/dmulyalin/fakenos/blob/master/fakenos/plugins/shell/cmd_shell.py#L121)
- `ret` never gets called and throws an attribute error [here](https://github.com/dmulyalin/fakenos/blob/master/fakenos/plugins/shell/cmd_shell.py#L157)

```shell
DEBUG:fakenos.plugins.servers.ssh_server_paramiko:ssh_server.channel_to_shell_tap sending line to shell: ['asdlfkj\r']
DEBUG:fakenos.plugins.shell.cmd_shell:shell.default 'cs01.area51' running command '['asdlfkj']'
ERROR:fakenos.plugins.shell.cmd_shell:shell.default 'cs01.area51' command '['asdlfkj']' not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/djustice/.pyenv/versions/3.7.16/lib/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CMDShell' object has no attribute 'do_asdlfkj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/djustice/.pyenv/versions/3.7.16/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/djustice/.pyenv/versions/3.7.16/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/djustice/venv/cat/lib/python3.7/site-packages/fakenos/plugins/servers/ssh_server_paramiko.py", line 290, in connection_function
    client_shell.start()
  File "/home/djustice/venv/cat/lib/python3.7/site-packages/fakenos/plugins/shell/cmd_shell.py", line 59, in start
    self.cmdloop()
  File "/home/djustice/.pyenv/versions/3.7.16/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/djustice/.pyenv/versions/3.7.16/lib/python3.7/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/djustice/venv/cat/lib/python3.7/site-packages/fakenos/plugins/shell/cmd_shell.py", line 158, in default
    ret = ret.format(
AttributeError: 'function' object has no attribute 'format'
```

**Comment by evilmonkey19** [comment]
I did not get exactly what you are trying to do, honestly 😅. Can you elaborate with an example?

**Comment by evilmonkey19** [comment]
Please, for the reply, refer to to the new repo [fakenos](https://github.com/fakenos/fakenos)

**Comment by dgjustice** [comment]
I have changed jobs since I was messing with this, and I forgot the context.  Thanks for following up.
